name: build-test
on:
  push: 
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install --no-install-recommends build-essential gettext gperf texinfo patch rsync xz-utils
      - run: ./bootstrap
      - run: ./configure
      - run: make
      - run: make check 
